export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRIES_BY_NAME = "GET_COUNTRIES_BY_NAME";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT"
export const SORT_BY_POPULATION = "SORT_BY_POPULATION";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const FILTER_BY_ACTIVITIES = "FILTER_BY_ACTIVITIES";
export const CREATE_ACTIVITY_FORM = "CREATE_ACTIVITY_FORM";